import Head from 'next/head';
import { HeaderMenuSideNav } from '../../molecules/HeaderMenuSideNav';
import * as theme from '../../../styles/theme'
import { Logo} from '../../atoms/Logo'
import { ButtonAdvertise } from '../../atoms/ButtonAdvertise';

export const Header = () => {
    return (
        <>
            <style jsx>{`
                header {
                    background-color: ${theme.mainColors.principal};
                    width: 100vw;
                    height: 70px;
                    top: 0;
                    left: 0;
                    padding: 30px;
                    display: flex;
                    align-items: center;
                    flex-direction: row;
                    justify-content: space-between;
                }

            `}</style>
            <Head>
                <title>Pai Véio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>

                <HeaderMenuSideNav />
                <Logo />
                <ButtonAdvertise />
            </header>
        </>
    )
};
